# Redis Cache Template
version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: exiled-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - exiled-network
    restart: unless-stopped

volumes:
  redis_data:
    driver: local