# SQL Server Database Template
version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: exiled-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_SA_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "${SQLSERVER_PORT:-1433}:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./scripts/sqlserver-init.sql:/opt/init.sql
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "${DB_SA_PASSWORD}" -Q "SELECT 1" || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - exiled-network
    restart: unless-stopped

volumes:
  sqlserver_data:
    driver: local