# Frontend Services Template
version: '3.8'

services:
  # Admin Panel (Vue.js)
  admin-panel:
    build:
      context: ./Frontend/admin-panel
      dockerfile: Dockerfile
    container_name: exiled-admin-panel
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=${API_BASE_URL:-http://localhost:5006}
      - VITE_GO_API_BASE_URL=${GO_API_BASE_URL:-http://localhost:8080}
      - VITE_SKINS_API_BASE_URL=${SKINS_API_BASE_URL:-http://localhost:8081}
    ports:
      - "${ADMIN_PORT:-3000}:80"
    depends_on:
      - cms-api
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - exiled-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    restart: unless-stopped

  # Public Website (Vue.js)
  webapp:
    build:
      context: ./Frontend/webapp
      dockerfile: Dockerfile
    container_name: exiled-webapp
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=${API_BASE_URL:-http://localhost:5006}
      - VITE_GO_API_BASE_URL=${GO_API_BASE_URL:-http://localhost:8080}
      - VITE_SKINS_API_BASE_URL=${SKINS_API_BASE_URL:-http://localhost:8081}
    ports:
      - "${WEBAPP_PORT:-8090}:80"
    depends_on:
      - cms-api
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - exiled-network
    deploy:
      replicas: ${WEBAPP_REPLICAS:-2}
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    restart: unless-stopped