# Load Balancer Template with SSL Support
version: '3.8'

services:
  # Nginx Load Balancer with SSL termination and backend SSL
  nginx:
    image: nginx:alpine
    container_name: exiled-nginx
    ports:
      - "${HTTP_PORT:-80}:80"              # HTTP (redirects to HTTPS)
      - "${HTTPS_PORT:-443}:443"           # Public HTTPS
      - "${NGINX_INTERNAL_PORT:-8443}:8443" # Internal HTTPS (mutual TLS)
      - "${NGINX_HEALTH_PORT:-8080}:8080"  # Health check port
    volumes:
      - ./ssl-infrastructure/service-configs/nginx-ssl.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl-certificates/services/nginx:/etc/ssl/certs:ro
      - ./ssl-certificates/services/nginx:/etc/ssl/private:ro
      - ./ssl-certificates/ca:/etc/ssl/ca:ro
      - ./ssl-certificates/services/clients:/etc/ssl/clients:ro
      - ./ssl-certificates/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
      - SSL_CERT_PATH=/etc/ssl/certs/nginx.crt
      - SSL_KEY_PATH=/etc/ssl/private/nginx.key
      - SSL_CA_PATH=/etc/ssl/ca/ca.crt
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/nginx-health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      exiled-network:
        aliases:
          - nginx.exiled.local
          - loadbalancer.exiled.local
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    restart: unless-stopped

  # SSL certificate watcher (for automatic reloading)
  nginx-ssl-watcher:
    image: alpine:latest
    container_name: exiled-nginx-ssl-watcher
    command: |
      sh -c '
        echo "Starting SSL certificate watcher..."
        while true; do
          inotifywait -e modify,create,delete /ssl-certificates/services/nginx/ 2>/dev/null
          echo "SSL certificates changed, reloading Nginx..."
          docker exec exiled-nginx nginx -s reload
          sleep 5
        done
      '
    volumes:
      - ./ssl-certificates/services/nginx:/ssl-certificates/services/nginx:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx
    restart: unless-stopped
    networks:
      - exiled-network