# Go Services Template with SSL Support
version: '3.8'

services:
  # High-Performance Go API with SSL
  go-api:
    build:
      context: ./GoServices/HighPerformanceAPI
      dockerfile: Dockerfile.ssl
    container_name: exiled-go-api
    environment:
      - GO_API_PORT=8080
      - GO_API_HTTPS_PORT=8443
      - GO_API_INTERNAL_PORT=8444
      - DATABASE_PROVIDER=${DATABASE_PROVIDER}
      - DATABASE_URL=${GO_DB_CONNECTION_STRING_SSL}
      - REDIS_URL=${REDIS_CONNECTION_STRING_SSL}
      - MAIN_API_URL=https://cms-api:8443
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - JWT_SECRET=${JWT_SECRET}
      # SSL configuration
      - SSL_CERT_FILE=/app/ssl/go-api.crt
      - SSL_KEY_FILE=/app/ssl/go-api.key
      - SSL_CA_FILE=/app/ssl/ca.crt
      - SSL_CLIENT_CERT_FILE=/app/ssl/clients/internal-client-client.crt
      - SSL_CLIENT_KEY_FILE=/app/ssl/clients/internal-client-client.key
      - SSL_VERIFY_PEER=true
      - SSL_MIN_VERSION=TLS1.2
    ports:
      - "${GO_API_PORT:-8080}:8080"           # HTTP (health checks only)
      - "${GO_API_SSL_PORT:-8443}:8443"       # Public HTTPS
      - "${GO_API_INTERNAL_PORT:-8444}:8444"  # Internal HTTPS (mutual TLS)
    volumes:
      - ./ssl-certificates/services/go-api:/app/ssl:ro
      - ./ssl-certificates/ca:/app/ssl-ca:ro
      - ./ssl-certificates/services/clients:/app/ssl/clients:ro
      - ./ssl-infrastructure/service-configs/go-api-ssl.yaml:/app/config-ssl.yaml:ro
    depends_on:
      - cms-api
      - ssl-init
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      exiled-network:
        aliases:
          - go-api.exiled.local
    deploy:
      replicas: ${GO_API_REPLICAS:-2}
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    restart: unless-stopped