apiVersion: 1

# This provisions a default Prometheus datasource pointing to the local Prometheus service.
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
